### PR TITLE
Some CS Changes for #8039

### PR DESCRIPTION
**Pull request by zero-24**
@xsability this should fix some CS to make the Code and the Comments more clear ;)

### CODE REVIEW

**Comment by xsability** [comment]
@zero-24, thank you for your patch. I am very sorry, I am new at github and I have fully forget to pull your Request on Github. I have pull it yet and I got the message, that your changes are done. I am not sure, but I hope now everything is fine. Again, sorry for my mistake.

**Comment by zero-24** [comment]
I have restored the fixes ;)

No problem. I have just cleaned my repo up. ;)

**Comment by xsability** [comment]
@zero-24, thx, now it works. The merge is done and i have pulled at my local repro. My be you want teach me a bit in github :-) . I have done already a pull request look here: https://github.com/joomla/joomla-cms/pull/8039 . I want that your changes get into yomlar cms too. Must I send a new pull request?

**Comment by zero-24** [comment]
No. All the changes you have merged here are in your PR if that PR gets merged all fixes goes in the main repo.

**Pull request merged**
